# Generated by Django 4.0.4 on 2022-04-19 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128)),
                ('technical_requirement', models.TextField()),
                ('customer', models.CharField(blank=True, max_length=64)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('start_of_the_project', models.DateField()),
                ('salary_per_hour', models.FloatField()),
                ('project_cost', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start_time', models.DateTimeField()),
                ('shift_end_time', models.DateTimeField()),
                ('shift_duration_time', models.DurationField(blank=True, null=True)),
                ('salary_per_shift', models.FloatField(blank=True, null=True)),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.project')),
            ],
        ),
    ]
