# Generated by Django 4.0.4 on 2022-04-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_alter_project_project_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_cost',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
