# Generated by Django 4.0.4 on 2022-04-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_alter_project_project_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_duration',
            field=models.DurationField(blank=True, default=0),
        ),
    ]
