# Generated by Django 4.0.4 on 2022-04-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_project_project_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_duration',
        ),
    ]
