# Generated by Django 4.0.4 on 2022-04-21 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0007_remove_project_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
